import type { ExerciseDef } from "@/lib/types";

export const EXERCISES: ExerciseDef[] = [
  {
    id: "ex-chin-tuck",
    slug: "chin-tuck",
    name: "Chin tuck",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "Stand or sit tall. Glide the head straight backward without looking down.",
    cues: ["Keep eyes level", "Make a gentle double-chin", "No force"],
    common_mistakes: ["Jutting the chin downward or extending the neck"],
    purpose: "Neck posture and cervical control",
  },
  {
    id: "ex-neck-rotation",
    slug: "neck-rotation",
    name: "Neck rotation",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "Turn the head slowly left and right through comfortable range.",
    cues: ["Stay tall", "Shoulders relaxed", "Move slowly"],
    common_mistakes: ["Forcing end range or rotating the torso"],
  },
  {
    id: "ex-wall-slide",
    slug: "wall-slide",
    name: "Wall slide",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "Back/forearms against wall where possible. Slide arms upward while keeping ribs controlled.",
    cues: ["Do not shrug", "Keep rib cage down", "Move pain-free"],
    common_mistakes: ["Arching the lower back to fake overhead range"],
  },
  {
    id: "ex-cat-cow",
    slug: "cat-cow",
    name: "Cat-cow",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "On hands and knees, alternate controlled spinal flexion and extension.",
    cues: ["Move segment by segment", "Breathe normally"],
    common_mistakes: ["Throwing the head or forcing lumbar extension"],
  },
  {
    id: "ex-open-book",
    slug: "open-book-rotation",
    name: "Open-book thoracic rotation",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "Side-lying with hips/knees bent, rotate top arm and chest open.",
    cues: ["Keep knees together", "Rotate through thoracic spine"],
    common_mistakes: ["Letting the pelvis roll excessively"],
  },
  {
    id: "ex-9090",
    slug: "90-90-hip-switch",
    name: "90/90 hip switch",
    category: "mobility",
    metric_type: "reps",
    instructions:
      "Sit with both knees bent at 90 degrees and rotate them side to side.",
    cues: ["Stay tall", "Control the transition"],
    common_mistakes: ["Using momentum or forcing painful hip range"],
  },
  {
    id: "ex-deep-squat",
    slug: "deep-squat-hold",
    name: "Deep squat hold",
    category: "mobility",
    metric_type: "hold",
    instructions: "Sit into a comfortable deep squat with feet planted.",
    cues: ["Knees track toes", "Heels stay down", "Torso relaxed"],
    common_mistakes: ["Collapsing onto painful joints"],
  },
  {
    id: "ex-ankle-rock",
    slug: "knee-over-toe-ankle-rock",
    name: "Knee-over-toe ankle rock",
    category: "mobility",
    metric_type: "reps",
    instructions: "Drive knee forward over toes while heel stays planted.",
    cues: ["Track knee in line with toes"],
    common_mistakes: ["Heel lifting or foot collapsing"],
  },
  {
    id: "ex-wrist-rocks",
    slug: "wrist-rocks",
    name: "Wrist rocks",
    category: "warmup",
    metric_type: "reps",
    instructions: "Rock wrists forward and laterally through comfortable range.",
    cues: ["Slow controlled motion", "Keep shoulders relaxed"],
    common_mistakes: ["Forcing painful end range"],
  },
  {
    id: "ex-scap-push",
    slug: "scapular-push-up",
    name: "Scapular push-up",
    category: "warmup",
    metric_type: "reps",
    instructions:
      "In plank, keep elbows straight and move shoulder blades apart/together.",
    cues: ["Push the floor away", "Ribs controlled"],
    common_mistakes: ["Bending elbows"],
  },
  {
    id: "ex-scap-pull",
    slug: "scapular-pull-up",
    name: "Scapular pull-up",
    category: "warmup",
    metric_type: "reps",
    instructions:
      "Hang with straight elbows; depress/retract shoulder blades to lift body slightly.",
    cues: ["Long arms", "Small controlled movement"],
    common_mistakes: ["Turning it into a partial pull-up"],
  },
  {
    id: "ex-arm-circles",
    slug: "arm-circles",
    name: "Arm circles",
    category: "warmup",
    metric_type: "reps",
    instructions: "Circle arms forward and backward through full comfortable range.",
    cues: ["Tall posture", "Smooth circles"],
    common_mistakes: ["Shrugging excessively"],
  },
  {
    id: "ex-hollow",
    slug: "hollow-hold",
    name: "Hollow-body hold",
    category: "warmup",
    metric_type: "hold",
    instructions: "Lie supine, flatten lower back, lift shoulders and legs.",
    cues: ["Lower back stays pressed down"],
    common_mistakes: ["Arching lumbar spine"],
  },
  {
    id: "ex-arch",
    slug: "arch-hold",
    name: "Arch hold",
    category: "warmup",
    metric_type: "hold",
    instructions: "Lie prone and lift chest/legs slightly with long body line.",
    cues: ["Glutes on", "Neck neutral"],
    common_mistakes: ["Cranking neck or lumbar spine"],
  },
  {
    id: "ex-air-squat",
    slug: "air-squat",
    name: "Air squat",
    category: "warmup",
    metric_type: "reps",
    instructions: "Squat with feet planted, knees tracking toes, stand tall.",
    cues: ["Heels down", "Chest up"],
    common_mistakes: ["Knees collapsing inward"],
  },
  {
    id: "ex-reverse-lunge",
    slug: "reverse-lunge",
    name: "Reverse lunge",
    category: "warmup",
    metric_type: "reps",
    instructions: "Step back into a lunge and return under control.",
    cues: ["Front knee tracks toes", "Torso upright"],
    common_mistakes: ["Short unstable steps"],
  },
  {
    id: "ex-oahs",
    slug: "oahs-practice",
    name: "OAHS practice block",
    category: "skill",
    metric_type: "skill_block",
    instructions:
      "Five-minute one-arm handstand protocol after the separate wrist warm-up: wall weight shifts, fingertip-assisted holds and high-quality free attempts. Terminate when alignment deteriorates.",
    cues: [
      "Push tall through support shoulder",
      "Keep stacked line",
      "Exit safely when line is lost",
    ],
    common_mistakes: [
      "Turning the block into fatigue training",
      "Twisting pelvis or collapsing shoulder",
    ],
    purpose: "One-arm handstand skill",
    progression_family: "oahs",
    pain_caution: "Stop if sharp wrist or shoulder pain appears.",
  },
  {
    id: "ex-wall-handstand",
    slug: "wall-handstand-hold",
    name: "Wall handstand hold",
    category: "skill",
    metric_type: "hold",
    instructions:
      "Hold a chest-to-wall handstand with a long stacked line and active shoulders.",
    cues: ["Push tall", "Ribs down", "Keep the line stacked"],
    common_mistakes: ["Arching hard through the lower back or collapsing the shoulders"],
    purpose: "OAHS-supporting handstand strength and line control",
  },
  {
    id: "ex-planche",
    slug: "planche-hold",
    name: "Planche practice block",
    category: "skill",
    metric_type: "skill_block",
    instructions:
      "Planche leans plus current planche-level holds with locked elbows and protraction.",
    cues: [
      "Locked elbows",
      "Rounded/protracted upper back",
      "Stop when form breaks",
    ],
    common_mistakes: ["Counting seconds after elbows bend or hips drop"],
    purpose: "Planche strength-skill",
    progression_family: "planche",
    pain_caution: "Tendon-heavy — do not force through sharp elbow/wrist pain.",
  },
  {
    id: "ex-flag",
    slug: "one-leg-human-flag",
    name: "One-leg human flag",
    category: "skill",
    metric_type: "hold",
    instructions:
      "Grip vertical support, press with lower arm and pull with upper arm while extending one leg.",
    cues: ["Shoulders active", "Pelvis stacked", "Train both sides"],
    common_mistakes: ["Twisting chest or hanging passively on shoulder"],
    progression_family: "human_flag",
  },
  {
    id: "ex-front-lever",
    slug: "front-lever-hold",
    name: "Front lever hold",
    category: "skill",
    metric_type: "hold",
    instructions:
      "Hold the current front-lever progression with straight elbows, depressed shoulders and a rigid hollow body.",
    cues: ["Straight elbows", "Pull the bar toward the hips", "Keep ribs and pelvis locked"],
    common_mistakes: ["Bent elbows", "Hips dropping", "Losing scapular control"],
    purpose: "Front-lever straight-arm pulling strength",
    progression_family: "front_lever",
  },
  {
    id: "ex-back-lever",
    slug: "back-lever-hold",
    name: "Back lever hold",
    category: "skill",
    metric_type: "hold",
    instructions:
      "Hold the current back-lever progression with locked elbows, active shoulders and a straight body line.",
    cues: ["Locked elbows", "Squeeze glutes", "Control shoulder extension"],
    common_mistakes: ["Sagging hips", "Relaxing into the shoulders", "Forcing painful shoulder range"],
    purpose: "Back-lever straight-arm strength and shoulder control",
    progression_family: "back_lever",
    pain_caution: "Stop if shoulder or biceps-tendon pain is sharp or increasing.",
  },
  {
    id: "ex-muscle-up",
    slug: "strict-muscle-up",
    name: "Strict muscle-up",
    category: "power",
    metric_type: "load_reps",
    instructions:
      "From controlled hang, pull explosively high, transition chest over bar, finish with straight-arm dip support.",
    cues: ["Keep path close to bar", "No uncontrolled kip"],
    common_mistakes: ["Chicken-wing transition or grinding slow reps"],
  },
  {
    id: "ex-clap-push",
    slug: "clap-push-up",
    name: "Clap push-up",
    category: "power",
    metric_type: "reps",
    instructions:
      "Lower under control and push explosively enough to clap before landing softly.",
    cues: ["Rigid trunk", "Hands return under shoulders"],
    common_mistakes: ["Sagging hips or stiff-elbow landing"],
  },
  {
    id: "ex-broad-jump",
    slug: "standing-broad-jump",
    name: "Standing broad jump",
    category: "power",
    metric_type: "distance",
    instructions:
      "Countermove, swing arms and jump forward, landing quietly in stable squat.",
    cues: ["Full reset each rep", "Stick landing"],
    common_mistakes: ["Repeated rebound jumps or unstable landing"],
  },
  {
    id: "ex-wpu",
    slug: "weighted-pull-up",
    name: "Weighted pull-up",
    category: "strength",
    metric_type: "load_reps",
    instructions:
      "Start from controlled hang and pull until chin clearly passes bar.",
    cues: ["Depress shoulders", "No leg swing", "Full controlled lower"],
    common_mistakes: ["Half reps or kipping"],
  },
  {
    id: "ex-hspu",
    slug: "handstand-push-up",
    name: "Handstand push-up progression",
    category: "strength",
    metric_type: "load_reps",
    instructions:
      "From handstand, lower head under control and press back to lockout using current progression level.",
    cues: ["Vertical line", "Active shoulders", "Controlled depth"],
    common_mistakes: ["Flaring excessively or losing trunk line"],
    progression_family: "hspu",
  },
  {
    id: "ex-bss",
    slug: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    category: "strength",
    metric_type: "load_reps",
    instructions:
      "Rear foot elevated, lower front leg until controlled depth, then stand.",
    cues: ["Front knee tracks toes", "Torso stable", "Drive through whole foot"],
    common_mistakes: ["Pushing excessively off rear leg"],
  },
  {
    id: "ex-single-leg-rdl",
    slug: "single-leg-rdl",
    name: "Single-leg Romanian deadlift",
    category: "strength",
    metric_type: "load_reps",
    instructions:
      "Stand on one leg, hinge at the hip while the free leg reaches back, then drive the hip forward to stand tall.",
    cues: ["Square the hips", "Soft knee", "Long spine", "Control the balance"],
    common_mistakes: ["Rotating the pelvis open", "Rounding the back", "Turning it into a squat"],
    purpose: "Posterior-chain strength, hip stability and single-leg balance",
  },
  {
    id: "ex-nordic",
    slug: "nordic-hamstring-curl",
    name: "Nordic hamstring curl",
    category: "strength",
    metric_type: "reps",
    instructions:
      "Kneel with ankles anchored, keep hips extended and lower body forward under hamstring control.",
    cues: ["Straight line knee-to-shoulder", "Use assistance as prescribed"],
    common_mistakes: ["Bending at hips to shorten lever"],
  },
  {
    id: "ex-hslr",
    slug: "hanging-straight-leg-raise",
    name: "Hanging straight-leg raise",
    category: "core",
    metric_type: "reps",
    instructions:
      "Hang and raise straight legs using abs/hip flexors without swinging.",
    cues: ["Posteriorly tilt pelvis at top", "Controlled lower"],
    common_mistakes: ["Kipping or momentum"],
  },
  {
    id: "ex-couch",
    slug: "couch-stretch",
    name: "Couch stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions:
      "Rear knee near wall/bench, rear foot elevated, squeeze glute and bring torso upright.",
    cues: ["Posterior pelvic tilt", "Glute on"],
    common_mistakes: ["Arching lumbar spine"],
  },
  {
    id: "ex-half-split",
    slug: "half-split",
    name: "Half-split hamstring stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions:
      "From kneeling lunge, shift hips back and straighten front leg.",
    cues: ["Long spine", "Hinge from hips"],
    common_mistakes: ["Rounding aggressively to reach farther"],
  },
  {
    id: "ex-front-split",
    slug: "front-split",
    name: "Front split",
    category: "flexibility",
    metric_type: "split",
    instructions:
      "Slide front heel forward and rear leg back while keeping hips as square as possible.",
    cues: ["Use supports", "Breathe", "No sharp pain"],
    common_mistakes: ["Forcing depth or twisting hips open"],
    progression_family: "front_split",
    pain_caution: "Never force through sharp hip or adductor pain.",
  },
  {
    id: "ex-pancake",
    slug: "pancake",
    name: "Pancake",
    category: "flexibility",
    metric_type: "hold",
    instructions: "Sit legs wide and hinge torso forward from hips.",
    cues: ["Long spine", "Active hip flexion"],
    common_mistakes: ["Rounding only through lower back"],
  },
  {
    id: "ex-middle-split",
    slug: "middle-split",
    name: "Middle split",
    category: "flexibility",
    metric_type: "split",
    instructions: "Slide legs apart laterally with support, controlling depth.",
    cues: ["Knees/toes positioned consistently", "Use blocks"],
    common_mistakes: ["Forcing depth or bouncing"],
    progression_family: "middle_split",
  },
  {
    id: "ex-easy-jog",
    slug: "easy-jog",
    name: "Easy jog",
    category: "warmup",
    metric_type: "duration",
    instructions: "Easy jog to raise temperature.",
    cues: ["Relaxed breathing", "Light footstrike"],
    common_mistakes: ["Starting too hard"],
  },
  {
    id: "ex-leg-swing-fb",
    slug: "leg-swings-front-back",
    name: "Leg swings front/back",
    category: "warmup",
    metric_type: "reps",
    instructions: "Swing leg forward and back through comfortable range.",
    cues: ["Tall posture", "Controlled amplitude"],
    common_mistakes: ["Twisting the torso"],
  },
  {
    id: "ex-leg-swing-lat",
    slug: "leg-swings-lateral",
    name: "Leg swings lateral",
    category: "warmup",
    metric_type: "reps",
    instructions: "Swing leg side to side through comfortable range.",
    cues: ["Support leg stable"],
    common_mistakes: ["Losing balance and rushing"],
  },
  {
    id: "ex-walking-lunge",
    slug: "walking-lunge",
    name: "Walking lunge",
    category: "warmup",
    metric_type: "reps",
    instructions:
      "Step forward into lunge, lower under control and drive into next step.",
    cues: ["Front knee tracks toes", "Torso stable"],
    common_mistakes: ["Short unstable steps or knee collapse"],
  },
  {
    id: "ex-ankle-pogo",
    slug: "ankle-pogo-hop",
    name: "Ankle pogo hop",
    category: "warmup",
    metric_type: "reps",
    instructions: "Small ankle bounces with short ground contact.",
    cues: ["Tall posture", "Quiet landing"],
    common_mistakes: ["Deep squat contacts"],
  },
  {
    id: "ex-high-knees",
    slug: "high-knees",
    name: "High knees",
    category: "warmup",
    metric_type: "duration",
    instructions: "Drive knees up rhythmically in place.",
    cues: ["Quick feet", "Upright torso"],
    common_mistakes: ["Sitting back"],
  },
  {
    id: "ex-butt-kicks",
    slug: "butt-kicks",
    name: "Butt kicks",
    category: "warmup",
    metric_type: "duration",
    instructions: "Kick heels toward glutes rhythmically.",
    cues: ["Relaxed shoulders"],
    common_mistakes: ["Overstriding"],
  },
  {
    id: "ex-pogo",
    slug: "pogo-jump",
    name: "Pogo jump",
    category: "power",
    metric_type: "reps",
    instructions:
      "Bounce vertically from ankles with small knee bend and short ground contact.",
    cues: ["Tall posture", "Springy ankles", "Quiet landing"],
    common_mistakes: ["Deep squat or slow contacts"],
  },
  {
    id: "ex-sprint",
    slug: "20m-acceleration-sprint",
    name: "20 m acceleration sprint",
    category: "power",
    metric_type: "distance",
    instructions: "Accelerate hard from a stable start through 20 m.",
    cues: ["Forward projection early", "Powerful arms", "Full recovery"],
    common_mistakes: ["Turning reps into fatigued conditioning"],
  },
  {
    id: "ex-shuttle",
    slug: "5-10-5-shuttle",
    name: "5-10-5 shuttle",
    category: "power",
    metric_type: "reps",
    instructions: "Sprint 5 m to one side, 10 m across, then 5 m through start.",
    cues: ["Lower center of mass before cuts", "Plant outside foot cleanly"],
    common_mistakes: ["Standing upright into change of direction"],
  },
  {
    id: "ex-pistol",
    slug: "pistol-squat",
    name: "Pistol squat",
    category: "strength",
    metric_type: "load_reps",
    instructions:
      "Single-leg squat to controlled depth and return without assistance unless current level requires it.",
    cues: ["Knee tracks toes", "Heel planted", "Torso controlled"],
    common_mistakes: ["Knee collapsing inward or bouncing off bottom"],
  },
  {
    id: "ex-glute-bridge",
    slug: "single-leg-glute-bridge",
    name: "Single-leg glute bridge",
    category: "strength",
    metric_type: "reps",
    instructions: "Lie supine, one foot planted, extend hip and pause at top.",
    cues: ["Ribs down", "Squeeze glute", "Pelvis level"],
    common_mistakes: ["Hyperextending lumbar spine"],
  },
  {
    id: "ex-copenhagen",
    slug: "copenhagen-plank",
    name: "Copenhagen plank",
    category: "strength",
    metric_type: "hold",
    instructions:
      "Side plank with top leg supported on bench/chair and lower leg free.",
    cues: ["Straight body", "Hips high", "Shoulder stacked"],
    common_mistakes: ["Letting hips rotate or drop"],
  },
  {
    id: "ex-calf",
    slug: "single-leg-calf-raise",
    name: "Single-leg calf raise",
    category: "strength",
    metric_type: "load_reps",
    instructions: "Rise fully onto forefoot on one leg and lower under control.",
    cues: ["Full range", "Stable ankle"],
    common_mistakes: ["Bouncing through reps"],
  },
  {
    id: "ex-tibialis",
    slug: "tibialis-wall-raise",
    name: "Tibialis wall raise",
    category: "strength",
    metric_type: "reps",
    instructions: "Lean on wall with heels planted and lift toes toward shins.",
    cues: ["Keep heels down", "Pause at top"],
    common_mistakes: ["Rocking whole body"],
  },
  {
    id: "ex-run-intervals",
    slug: "strong-easy-intervals",
    name: "Strong/easy intervals",
    category: "endurance",
    metric_type: "duration",
    instructions:
      "Run the prescribed number of strong repetitions. Each strong repetition is followed by the prescribed easy-jog recovery before the next strong repetition.",
    cues: ["Strong = RPE 7–8/10, controlled rather than sprinting", "Easy jog = RPE 2–3/10", "Keep every strong repetition similar in quality"],
    common_mistakes: ["Starting the first interval too fast", "Making easy recoveries too hard", "Turning strong intervals into maximal sprints"],
  },
  {
    id: "ex-steady-run",
    slug: "steady-continuous-run",
    name: "Steady continuous run",
    category: "endurance",
    metric_type: "duration",
    instructions: "Continuous steady run at prescribed effort.",
    cues: ["Even effort", "Relaxed shoulders"],
    common_mistakes: ["Positive split from starting too fast"],
  },
  {
    id: "ex-easy-run",
    slug: "easy-continuous-run",
    name: "Easy continuous run",
    category: "endurance",
    metric_type: "duration",
    instructions: "Easy continuous run; conversational effort.",
    cues: ["Nose breathing possible", "Soft landings"],
    common_mistakes: ["Pushing pace"],
  },
  {
    id: "ex-deload-run",
    slug: "very-easy-deload-run",
    name: "Very easy deload run",
    category: "endurance",
    metric_type: "duration",
    instructions: "Very easy recovery run. No progression.",
    cues: ["Truly easy"],
    common_mistakes: ["Treating deload as a hard session"],
  },
  {
    id: "ex-frog",
    slug: "frog-stretch",
    name: "Frog stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions:
      "On forearms/hands and knees, widen knees and move hips back gently.",
    cues: ["Neutral spine", "Controlled range"],
    common_mistakes: ["Forcing groin stretch sharply"],
  },
  {
    id: "ex-pullup",
    slug: "pull-up",
    name: "Pull-up",
    category: "volume",
    metric_type: "load_reps",
    instructions: "Controlled hang to chin over bar and back to full extension.",
    cues: ["No swing", "Consistent ROM"],
    common_mistakes: ["Kipping or shortened lower"],
  },
  {
    id: "ex-dip",
    slug: "parallel-bar-dip",
    name: "Parallel-bar dip",
    category: "volume",
    metric_type: "load_reps",
    instructions:
      "From straight-arm support, lower shoulders below elbows as comfortable and press to lockout.",
    cues: ["Shoulders active", "Controlled depth"],
    common_mistakes: ["Dropping fast or shrugging at top"],
  },
  {
    id: "ex-inv-row",
    slug: "inverted-row",
    name: "Inverted row",
    category: "volume",
    metric_type: "reps",
    instructions: "Body straight under bar/rings; pull chest to hands/bar.",
    cues: ["Squeeze shoulder blades", "Rigid body"],
    common_mistakes: ["Hips sagging"],
  },
  {
    id: "ex-pushup",
    slug: "push-up",
    name: "Push-up",
    category: "volume",
    metric_type: "load_reps",
    instructions: "Body straight, lower chest near floor, press to full lockout.",
    cues: ["Elbows controlled", "Ribs and pelvis aligned"],
    common_mistakes: ["Sagging hips or partial depth"],
  },
  {
    id: "ex-dragon",
    slug: "dragon-flag",
    name: "Dragon flag",
    category: "core",
    metric_type: "reps",
    instructions:
      "Brace on bench/support, raise rigid body and lower slowly as one unit.",
    cues: ["Posterior pelvic tilt", "Controlled 3-sec lower"],
    common_mistakes: ["Bending hips to make rep easier"],
  },
  {
    id: "ex-burpee",
    slug: "burpee",
    name: "Burpee",
    category: "conditioning",
    metric_type: "reps",
    instructions: "Squat to hands, move feet to plank, return and stand/jump.",
    cues: ["Smooth rhythm", "Stable plank"],
    common_mistakes: ["Losing trunk control under fatigue"],
  },
  {
    id: "ex-mountain",
    slug: "mountain-climber",
    name: "Mountain climber",
    category: "conditioning",
    metric_type: "reps",
    instructions: "From plank, alternate driving knees forward.",
    cues: ["Shoulders over hands", "Hips stable"],
    common_mistakes: ["Bouncing hips high"],
  },
  {
    id: "ex-cossack",
    slug: "cossack-squat",
    name: "Cossack squat",
    category: "flexibility",
    metric_type: "reps",
    instructions: "Shift into deep side squat while opposite leg stays straight.",
    cues: ["Working foot planted", "Knee tracks toes"],
    common_mistakes: ["Collapsing knee inward"],
  },
  {
    id: "ex-dead-bug",
    slug: "dead-bug",
    name: "Dead bug",
    category: "core",
    metric_type: "reps",
    instructions:
      "Supine with hips/knees 90 degrees; extend opposite arm/leg without losing trunk position.",
    cues: ["Lower back controlled", "Slow reps"],
    common_mistakes: ["Arching as limb extends"],
  },
  {
    id: "ex-bird-dog",
    slug: "bird-dog",
    name: "Bird dog",
    category: "core",
    metric_type: "reps",
    instructions: "On hands/knees, extend opposite arm and leg and hold.",
    cues: ["Pelvis square", "Reach long"],
    common_mistakes: ["Rotating trunk"],
  },
  {
    id: "ex-knee-wall",
    slug: "knee-to-wall-ankle",
    name: "Knee-to-wall ankle mobilization",
    category: "mobility",
    metric_type: "reps",
    instructions: "Drive knee toward wall while heel stays down.",
    cues: ["Track knee over toes"],
    common_mistakes: ["Heel lift"],
  },
  {
    id: "ex-calf-stretch",
    slug: "calf-stretch",
    name: "Calf stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions: "Stretch calf with heel down and knee soft or straight as needed.",
    cues: ["Gentle continuous tension"],
    common_mistakes: ["Bouncing"],
  },
  {
    id: "ex-seated-lift",
    slug: "straight-leg-seated-lift",
    name: "Straight-leg seated lift",
    category: "strength",
    metric_type: "reps",
    instructions:
      "Sit tall with one/both legs straight and actively lift heel off floor.",
    cues: ["Keep knee locked", "Use hip flexors"],
    common_mistakes: ["Leaning back excessively"],
  },
  {
    id: "ex-easy-free",
    slug: "easy-freestyle",
    name: "Easy freestyle",
    category: "swim",
    metric_type: "swim",
    instructions: "Easy freestyle swimming for prescribed distance.",
    cues: ["Relaxed stroke", "Steady breathing"],
    common_mistakes: ["Rushing recovery"],
  },
  {
    id: "ex-catchup",
    slug: "catch-up-freestyle",
    name: "Catch-up freestyle drill",
    category: "swim",
    metric_type: "swim",
    instructions:
      "Swim freestyle with one hand waiting forward until the other hand reaches it before the next stroke.",
    cues: ["Long body line", "Relaxed kick", "Focus on catch timing"],
    common_mistakes: ["Pausing so much that body sinks"],
  },
  {
    id: "ex-strong-free",
    slug: "strong-controlled-freestyle",
    name: "Strong controlled freestyle",
    category: "swim",
    metric_type: "swim",
    instructions: "Strong but controlled freestyle repeats.",
    cues: ["Quality stroke", "Full recovery"],
    common_mistakes: ["Sacrificing form for speed"],
  },
  {
    id: "ex-fast-free",
    slug: "fast-freestyle",
    name: "Fast freestyle",
    category: "swim",
    metric_type: "swim",
    instructions: "Fast freestyle repeats with full rest.",
    cues: ["Explosive but controlled"],
    common_mistakes: ["Incomplete rest"],
  },
  {
    id: "ex-breath3",
    slug: "freestyle-breathing-3",
    name: "Freestyle breathing every 3 strokes",
    category: "swim",
    metric_type: "swim",
    instructions:
      "Swim normal freestyle and breathe every third arm stroke, alternating sides.",
    cues: ["Exhale continuously underwater", "Relaxed breath"],
    common_mistakes: ["Holding breath underwater or forcing pace"],
    pain_caution:
      "Do not prescribe unsupervised underwater breath-hold repetitions.",
  },
  {
    id: "ex-backstroke",
    slug: "backstroke",
    name: "Backstroke",
    category: "swim",
    metric_type: "swim",
    instructions: "Easy to moderate backstroke.",
    cues: ["Long body", "Relaxed neck"],
    common_mistakes: ["Sitting in the water"],
  },
  {
    id: "ex-wrist-circles",
    slug: "wrist-circles",
    name: "Wrist circles",
    category: "warmup",
    metric_type: "reps",
    instructions: "Circle wrists each direction.",
    cues: ["Slow and controlled"],
    common_mistakes: ["Forcing pain"],
  },
  {
    id: "ex-finger-oc",
    slug: "finger-open-close",
    name: "Finger open/close",
    category: "warmup",
    metric_type: "reps",
    instructions: "Open and close fingers fully.",
    cues: ["Full ROM"],
    common_mistakes: ["Rushing"],
  },
  {
    id: "ex-climb-easy",
    slug: "easy-climb-problems",
    name: "Easy problems/routes",
    category: "climb",
    metric_type: "climb",
    instructions: "Warm-up on easy terrain.",
    cues: ["Relaxed grip", "Precise feet"],
    common_mistakes: ["Jumping into hard grades cold"],
  },
  {
    id: "ex-climb-harder",
    slug: "harder-climb-problems",
    name: "Slightly harder problems/routes",
    category: "climb",
    metric_type: "climb",
    instructions: "Slightly harder warm-up climbs.",
    cues: ["Read sequence", "Full rest"],
    common_mistakes: ["Pumping out before quality work"],
  },
  {
    id: "ex-climb-quality",
    slug: "climbing-quality-attempt",
    name: "Climbing quality attempt",
    category: "climb",
    metric_type: "climb",
    instructions:
      "Make one deliberate attempt on the assigned problem with full focus, then rest.",
    cues: ["Read sequence first", "Precise feet"],
    common_mistakes: ["Rapid repeated attempts without recovery"],
  },
  {
    id: "ex-climb-endurance",
    slug: "continuous-easy-climbing",
    name: "Continuous easy climbing",
    category: "climb",
    metric_type: "duration",
    instructions: "Stay on easy terrain continuously for assigned time.",
    cues: ["Efficient feet", "Relaxed grip", "Straight arms when possible"],
    common_mistakes: ["Choosing terrain too hard to sustain"],
  },
  {
    id: "ex-band-finger",
    slug: "band-finger-extension",
    name: "Band finger extension",
    category: "recovery",
    metric_type: "reps",
    instructions: "Open fingers against an elastic band around fingertips.",
    cues: ["Full opening", "Controlled return"],
    common_mistakes: ["Snapping band or rushing"],
  },
  {
    id: "ex-flexor",
    slug: "flexor-stretch",
    name: "Flexor stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions: "Gentle forearm flexor stretch.",
    cues: ["No sharp pain"],
    common_mistakes: ["Forcing end range"],
  },
  {
    id: "ex-extensor",
    slug: "extensor-stretch",
    name: "Extensor stretch",
    category: "flexibility",
    metric_type: "hold",
    instructions: "Gentle forearm extensor stretch.",
    cues: ["No sharp pain"],
    common_mistakes: ["Forcing end range"],
  },
  {
    id: "ex-shoulder-circles",
    slug: "shoulder-circles",
    name: "Shoulder circles",
    category: "warmup",
    metric_type: "reps",
    instructions: "Circle shoulders each direction.",
    cues: ["Relaxed neck"],
    common_mistakes: ["Rushing"],
  },
  {
    id: "ex-bw-squat",
    slug: "bodyweight-squat",
    name: "Bodyweight squat",
    category: "warmup",
    metric_type: "reps",
    instructions: "Bodyweight squat with full control.",
    cues: ["Knees track toes"],
    common_mistakes: ["Heels lifting"],
  },
];

export function getExerciseBySlug(slug: string): ExerciseDef | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}

export function getExerciseById(id: string): ExerciseDef | undefined {
  return EXERCISES.find((e) => e.id === id);
}
