import type { ProgressionRuleDef } from "@/lib/types";

export const PROGRESSION_RULES: ProgressionRuleDef[] = [
  {
    id: "rule-oahs",
    code: "OAHS_V1",
    name: "OAHS assistance progression",
    version: 1,
    description:
      "Yes = +1 skill credit. After 3 successful sessions with both sides completing assisted attempts and one clean free attempt, advance assistance level.",
    scope: "global_skill",
  },
  {
    id: "rule-planche",
    code: "PLANCHE_V1",
    name: "Planche hard-session progression",
    version: 1,
    description:
      "Hard Yes = +1 hard credit. After 2 successful hard sessions at full holds, advance level and reset hold durations.",
    scope: "global_skill",
  },
  {
    id: "rule-flag",
    code: "HUMAN_FLAG_V1",
    name: "Human flag hold progression",
    version: 1,
    description:
      "Success adds +1 sec to that workout context (cap 10). Both Mon/Sat at 10 sec completed once advances level.",
    scope: "global_skill",
  },
  {
    id: "rule-front-lever",
    code: "FRONT_LEVER_V1",
    name: "Front lever progression",
    version: 1,
    description:
      "Three clean successful sessions at the current progression advance one level; failed or maximal-quality sessions hold the level.",
    scope: "global_skill",
  },
  {
    id: "rule-back-lever",
    code: "BACK_LEVER_V1",
    name: "Back lever progression",
    version: 1,
    description:
      "Three clean successful sessions at the current progression advance one level; failed or painful sessions hold the level.",
    scope: "global_skill",
  },
  {
    id: "rule-front-split",
    code: "FRONT_SPLIT_V1",
    name: "Front split floor-gap progression",
    version: 1,
    description:
      "Successful moderate/deep session earns 1 credit. After 2 credits, reduce floor gap by 1 cm per side.",
    scope: "global_skill",
  },
  {
    id: "rule-middle-split",
    code: "MIDDLE_SPLIT_V1",
    name: "Middle split floor-gap progression",
    version: 1,
    description: "After 2 successful deep sessions, reduce target by 1 cm.",
    scope: "global_skill",
  },
  {
    id: "rule-mobility",
    code: "MOBILITY_MAINTAIN_V1",
    name: "Maintenance mobility quality",
    version: 1,
    description: "Keep exact reps. Mark quality maintained; do not add volume.",
    scope: "routine_item",
  },
  {
    id: "rule-mu",
    code: "STRICT_MUSCLE_UP_V1",
    name: "Strict muscle-up load",
    version: 1,
    description: "After 2 successful clean 4x3 sessions, +1 kg. Two failures: -1 kg.",
    scope: "routine_item",
  },
  {
    id: "rule-clap",
    code: "CLAP_PUSHUP_V1",
    name: "Clap push-up quality",
    version: 1,
    description: "After 3 successful sessions, advance explosive variation level.",
    scope: "routine_item",
  },
  {
    id: "rule-broad",
    code: "BROAD_JUMP_V1",
    name: "Broad jump distance",
    version: 1,
    description: "Next target = prior median x 1.01, rounded to nearest cm.",
    scope: "routine_item",
  },
  {
    id: "rule-wpu",
    code: "WEIGHTED_PULLUP_4X5_V1",
    name: "Weighted pull-up 4x5",
    version: 1,
    description: "Success +1 kg. Failure hold. Two consecutive failures -2 kg.",
    scope: "routine_item",
  },
  {
    id: "rule-hspu",
    code: "HSPU_LEVEL_V1",
    name: "HSPU level and reps",
    version: 1,
    description: "4x5→4x6→4x7 then advance level and reset 4x5.",
    scope: "routine_item",
  },
  {
    id: "rule-bss",
    code: "BULGARIAN_SPLIT_V1",
    name: "Bulgarian split squat load",
    version: 1,
    description: "Success +2 kg. Two failures -2 kg.",
    scope: "routine_item",
  },
  {
    id: "rule-nordic",
    code: "NORDIC_CURL_V1",
    name: "Nordic curl assistance/tempo",
    version: 1,
    description: "Success reduces assistance or lengthens eccentric.",
    scope: "routine_item",
  },
  {
    id: "rule-hslr",
    code: "HANGING_SLR_V1",
    name: "Hanging straight-leg raise",
    version: 1,
    description: "3x10→11→12 then toes-to-bar progression.",
    scope: "routine_item",
  },
  {
    id: "rule-pogo",
    code: "POGO_JUMP_V1",
    name: "Pogo jump quality level",
    version: 1,
    description: "3 successful sessions advance stiffness/height level.",
    scope: "routine_item",
  },
  {
    id: "rule-sprint",
    code: "SPRINT_20M_V1",
    name: "20 m sprint target",
    version: 1,
    description: "Next target = best x 0.995 if consistency criteria met.",
    scope: "routine_item",
  },
  {
    id: "rule-shuttle",
    code: "SHUTTLE_5105_V1",
    name: "5-10-5 shuttle target",
    version: 1,
    description: "Next target = best x 0.995 if consistency criteria met.",
    scope: "routine_item",
  },
  {
    id: "rule-pistol",
    code: "PISTOL_SQUAT_V1",
    name: "Pistol squat load",
    version: 1,
    description: "Success +1 kg next Wednesday.",
    scope: "routine_item",
  },
  {
    id: "rule-glute",
    code: "GLUTE_BRIDGE_V1",
    name: "Single-leg glute bridge",
    version: 1,
    description: "Reps to 15 then feet-elevated reset.",
    scope: "routine_item",
  },
  {
    id: "rule-single-leg-rdl",
    code: "SINGLE_LEG_RDL_V1",
    name: "Single-leg Romanian deadlift",
    version: 1,
    description: "Complete 3×8 cleanly on both legs: +2 kg next time. Failure holds load.",
    scope: "routine_item",
  },
  {
    id: "rule-copenhagen",
    code: "COPENHAGEN_V1",
    name: "Copenhagen plank hold",
    version: 1,
    description: "+5 sec to 30 then longer-lever variation.",
    scope: "routine_item",
  },
  {
    id: "rule-calf",
    code: "CALF_RAISE_V1",
    name: "Single-leg calf raise",
    version: 1,
    description: "+1 rep to 20 then +5 kg reset 15.",
    scope: "routine_item",
  },
  {
    id: "rule-tib",
    code: "TIBIALIS_V1",
    name: "Tibialis wall raise",
    version: 1,
    description: "+2 reps to 30 then move feet 5 cm and reset.",
    scope: "routine_item",
  },
  {
    id: "rule-run-w1",
    code: "RUN_INTERVALS_V1",
    name: "Week 1 interval pace",
    version: 1,
    description: "Start 6×(2:00 strong, 2:00 easy). Successful sessions reduce easy recovery by 10s to 90s, then add rounds to 8, then improve strong pace by ~5 sec/km.",
    scope: "capability",
  },
  {
    id: "rule-run-w2",
    code: "RUN_STEADY_V1",
    name: "Week 2 steady run",
    version: 1,
    description: "Success ≤7/10: +2 min until 30, then pace.",
    scope: "capability",
  },
  {
    id: "rule-run-w3",
    code: "RUN_LONG_V1",
    name: "Week 3 long easy run",
    version: 1,
    description: "Success +5 min until 60, then pace.",
    scope: "capability",
  },
  {
    id: "rule-run-w4",
    code: "RUN_DELOAD_V1",
    name: "Week 4 deload run",
    version: 1,
    description: "No progression.",
    scope: "capability",
  },
  {
    id: "rule-pullup-vol",
    code: "PULLUP_VOLUME_V1",
    name: "Pull-up volume",
    version: 1,
    description: "4x10→12 then +2 kg reset 4x8.",
    scope: "routine_item",
  },
  {
    id: "rule-dip-vol",
    code: "DIP_VOLUME_V1",
    name: "Dip volume",
    version: 1,
    description: "4x12→15 then +2 kg reset 4x10.",
    scope: "routine_item",
  },
  {
    id: "rule-inv-row",
    code: "INVERTED_ROW_V1",
    name: "Inverted row",
    version: 1,
    description: "3x12→15 then advance angle and reset.",
    scope: "routine_item",
  },
  {
    id: "rule-pushup-vol",
    code: "PUSHUP_VOLUME_V1",
    name: "Push-up volume",
    version: 1,
    description: "+2 reps to 30 then +5 kg vest reset 20.",
    scope: "routine_item",
  },
  {
    id: "rule-lunge-vol",
    code: "WALKING_LUNGE_V1",
    name: "Walking lunge volume",
    version: 1,
    description: "Reps to 15 then +4 kg reset 12.",
    scope: "routine_item",
  },
  {
    id: "rule-dragon",
    code: "DRAGON_FLAG_V1",
    name: "Dragon flag",
    version: 1,
    description: "3x6→8 then +0.5 kg ankle and reset.",
    scope: "routine_item",
  },
  {
    id: "rule-circuit",
    code: "BURPEE_CLIMBER_V1",
    name: "Burpee + mountain climber circuit",
    version: 1,
    description: "Reduce rest then raise reps pattern.",
    scope: "routine_item",
  },
  {
    id: "rule-swim-perf",
    code: "SWIM_PERFORMANCE_V1",
    name: "Performance swim volume",
    version: 1,
    description: "Success adds one 50 m strong repeat until 1200 m, then reduce rest.",
    scope: "capability",
  },
  {
    id: "rule-swim-rec",
    code: "SWIM_RECOVERY_V1",
    name: "Recovery swim",
    version: 1,
    description: "No overload progression.",
    scope: "capability",
  },
  {
    id: "rule-climb-quality",
    code: "CLIMB_QUALITY_V1",
    name: "Climbing problem grades",
    version: 1,
    description: "Complete in 1–2 attempts advances grade; attempt 3 or fail holds.",
    scope: "capability",
  },
  {
    id: "rule-climb-end",
    code: "CLIMB_ENDURANCE_V1",
    name: "Climbing endurance",
    version: 1,
    description: "+30 sec to 6 min then raise grade and reset 4 min.",
    scope: "capability",
  },
];

export function getRuleByCode(code: string): ProgressionRuleDef | undefined {
  return PROGRESSION_RULES.find((r) => r.code === code);
}
